name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            web/package-lock.json

      # サーバ側
      - run: npm ci
      - run: npm run typecheck
      - run: npm run test

      # フロント側
      - run: npm ci --prefix web
      - run: npm run lint --prefix web
      - run: npm run test --prefix web
      - run: npm run build --prefix web
